### ISSUE TITLE
Can the option to adjust the badge diameter be added? The badge has a ghosting issue.

### ISSUE THREAD

**Issue by wjlyl** [0xkuj/NotificationsGroupCount#1] opened 2024-10-31 00:11 UTC
![image](https://github.com/user-attachments/assets/4be4ce37-bf2d-424c-9a1a-9559f3fd4bc4)

**Comment by 0xkuj** [comment] 2024-10-31 08:01
what ios and device this is happening?

**Comment by wjlyl** [comment] 2024-11-01 00:14
> what ios and device this is happening?

13promax 15.0.2

**Comment by wjlyl** [comment] 2024-11-01 00:34
![image](https://github.com/user-attachments/assets/84b11ad1-19a2-4cd9-b9cf-f7d287a3e6e7)

**Comment by hoyoocc** [comment] 2024-11-01 09:17
Do you support rooted devices?

**Comment by 0xkuj** [comment] 2024-11-01 09:32
Issue was identified and will be fixed in later version

**Comment by hoyoocc** [comment] 2024-11-01 09:33
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by 0xkuj** [comment] 2024-11-01 10:00
@wjlyl hopefully fixed in 1.0.1, refresh your sources and try again.
let me know if this is solved!

**Comment by wjlyl** [comment] 2024-11-01 11:57
> @wjlyl hopefully fixed in 1.0.1, refresh your sources and try again.
> 
> let me know if this is solved!

The problem still exists.

**Comment by wjlyl** [comment] 2024-11-01 11:58
![image](https://github.com/user-attachments/assets/01a045c6-8996-4be7-9919-ba3e8e049ee4)

**Comment by 0xkuj** [comment] 2024-11-01 12:02
oh i just noticed you have trasnparent notifications.. ill check it out maybe i just cant see it

**Comment by 0xkuj** [comment] 2024-11-01 12:35
@wjlyl please test version 1.0.2, it should be fixed!

**Comment by wjlyl** [comment] 2024-11-01 13:13
> @wjlyl please test version 1.0.2, it should be fixed!

It seems that 1.0.2 has resolved the issue. I'll observe it a bit longer. Thank you for your hard work.

**Comment by 0xkuj** [comment] 2024-11-01 13:36
thanks. please close this if its all good @wjlyl

**Comment by wjlyl** [comment] 2024-11-01 13:44
> thanks. please close this if its all good @wjlyl 

The badge shadow has been fixed, and now the badge occasionally appears in the top left corner.![image](https://github.com/user-attachments/assets/a36393f8-01ea-459c-831a-987b97163947)

**Comment by 0xkuj** [comment] 2024-11-01 20:01
@wjlyl please test version 1.0.4, this was happening due to the icon not ready, hence giving us 0,0 as position.
i added a small unnoticed delay that should fix this.
please check 1.0.4 and let me know

i reverted changes, it caused regression.
i am checking into that. will update.

**Comment by wjlyl** [comment] 2024-11-02 03:38
> @wjlyl please test version 1.0.4, this was happening due to the icon not ready, hence giving us 0,0 as position.
> i added a small unnoticed delay that should fix this.
> please check 1.0.4 and let me know
> 
> i reverted changes, it caused regression.
> i am checking into that. will update.

Waiting for your update, thank you for your hard work.

**Comment by 0xkuj** [comment] 2024-11-18 11:54
should be fixed in 1.0.5. please reopen if needed

**Comment by hoyoocc** [comment] 2024-11-18 11:55
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Closed as completed by 0xkuj** 2024-11-18 11:54 UTC
Labels: bug
